# Generated by Django 5.0.2 on 2024-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='source',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
    ]
