# Generated by Django 5.0.2 on 2024-02-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_date_booked_booking_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_seats',
            field=models.IntegerField(default=60),
        ),
    ]
